"""Bundle the user's downloaded fonts as lossless WOFF2; never fetch substitute fonts.

Run: uv run --with fonttools --with brotli python scripts/prepare-fonts.py [source-dir]
"""
from concurrent.futures import ProcessPoolExecutor
from pathlib import Path
import json
import shutil
import sys
from fontTools.ttLib import TTFont

ROOT = Path(__file__).resolve().parents[1]
SOURCE = Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT.parent / "字体下载"
DEST = ROOT / "public/fonts/local"
FAMILIES = [
    ("source-han-sans", "思源黑体", "Source Han Sans SC", "sans-serif", "思源黑体-SC-2.005", "OTF/SimplifiedChinese/*.otf", "LICENSE.txt"),
    ("source-han-serif", "思源宋体", "Source Han Serif SC", "serif", "思源宋体-SC-2.003", "OTF/SimplifiedChinese/*.otf", "LICENSE.txt"),
    ("alibaba-puhuiti", "阿里巴巴普惠体", "Alibaba PuHuiTi 3", "sans-serif", "阿里巴巴普惠体-3.0", "网页字体/*.woff2", "下载与安装说明.txt"),
    ("noto-sans-sc", "Noto Sans SC", "Noto Sans SC", "sans-serif", "NotoSansSC-2.004", "OTF/*.otf", "官方说明/LICENSE"),
]


def convert(job):
    source, destination = map(Path, job)
    font = TTFont(source)
    weight = font["OS/2"].usWeightClass
    codepoints = sorted(font.getBestCmap())
    glyphs = len(codepoints)
    if destination.exists() and destination.stat().st_mtime >= source.stat().st_mtime:
        pass
    elif source.suffix == ".woff2":
        shutil.copy2(source, destination)
    else:
        font.flavor = "woff2"
        font.save(destination)
    font.close()
    ranges = []
    if "Alibaba" in source.name:
        start = end = codepoints[0]
        for point in codepoints[1:] + [0x110000]:
            if point == end + 1:
                end = point
                continue
            ranges.append(f"U+{start:X}" if start == end else f"U+{start:X}-{end:X}")
            start = end = point
    return {"weight": weight, "url": "/fonts/local/" + destination.name,
            "source": str(source.relative_to(SOURCE)), "characters": glyphs,
            "bytes": destination.stat().st_size,
            **({"family": "Alibaba PuHuiTi 3 L3"} if "RegularL3" in source.name else {}),
            **({"unicodeRange": ",".join(ranges)} if ranges else {})}


if __name__ == "__main__":
    DEST.mkdir(parents=True, exist_ok=True)
    manifest, css = [], []
    with ProcessPoolExecutor(max_workers=3) as pool:
        for slug, label, family, fallback, directory, pattern, license_path in FAMILIES:
            files = sorted((SOURCE / directory).glob(pattern))
            if not files:
                raise FileNotFoundError(directory)
            jobs = [(str(p), str(DEST / (p.stem + ".woff2"))) for p in files]
            faces = sorted(pool.map(convert, jobs), key=lambda face: face["weight"])
            notice = f"/fonts/local/{slug}-NOTICE.txt"
            shutil.copy2(SOURCE / directory / license_path, ROOT / "public" / notice.lstrip("/"))
            extension = '"Alibaba PuHuiTi 3 L3", ' if slug == "alibaba-puhuiti" else ""
            manifest.append({"id": slug, "label": label, "family": family,
                             "value": f'"{family}", {extension}{fallback}', "license": notice,
                             "faces": [{k: v for k, v in face.items() if k != "unicodeRange"} for face in faces]})
            for face in faces:
                coverage = f' unicode-range: {face["unicodeRange"]};' if "unicodeRange" in face else ""
                css.append(f'@font-face {{ font-family: "{face.get("family", family)}"; font-style: normal; '
                           f'font-weight: {face["weight"]}; font-display: swap; '
                           f'src: url("{face["url"]}") format("woff2");{coverage} }}')
            print(label, len(faces), "weights", round(sum(f["bytes"] for f in faces) / 1024**2, 1), "MiB", flush=True)
    (ROOT / "src/fontManifest.json").write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + "\n")
    (ROOT / "public/fonts/local/fonts.css").write_text("/* Generated by scripts/prepare-fonts.py. */\n" + "\n".join(css) + "\n")
